// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMHMGe8z_HXppevvxOubyD-d6Qtixn44Y',
    appId: '1:969384738690:web:14b0997623475150c6d99b',
    messagingSenderId: '969384738690',
    projectId: 'fitsync-57bea',
    authDomain: 'fitsync-57bea.firebaseapp.com',
    storageBucket: 'fitsync-57bea.firebasestorage.app',
    measurementId: 'G-FMRW8H00KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbcpfjY7IRAd_UU0p9NoSLdRENdOSNdcw',
    appId: '1:969384738690:android:1a3c3d5cc084c992c6d99b',
    messagingSenderId: '969384738690',
    projectId: 'fitsync-57bea',
    storageBucket: 'fitsync-57bea.firebasestorage.app',
  );
}
